spring:
  redis:
    cluster:
      nodes:
         - 127.0.0.1:6359
    standalone:
      host: localhost
      port: 6379

  couchbase:
    bucket:
      name: default
      password:
    errorBucket:
      name: errorBucket
      password:
    nodes:
      - 127.0.0.1:9091