server:
  port: 8080

#Default Application Domain
application:
  domain: com.target.commerce.objectionable.content.filter.http://localhost:${server.port}

spring:
  couchbase:
    nodes:
     - 127.0.0.0:8091
    bucket:
      name: badWordsBucket
      password: badWordsBucket
  jmx:
    enabled: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    templates_root: src/main/resources/templates/

#management endpoints on a separate port
management:
  port: 8092
  security:
    enabled: false # management port is internal only. no need to secure it.